name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "1bceb53f-5893-4bb0-a53f-7abb807b8f38"

[[kv_namespaces]]
binding = "kv"
id = "b0b6379a6e3a4ebdaec6dd46f8701e60"

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

#[[send_email]]
#name = "email"			#CF发件, 配置后优先使用

[ai]
binding = "ai"

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#每天晚上12点执行每日任务,刷新分析缓存


[vars]
add_email = 1
add_email_verify = 1
admin = "admin@djxs.xyz"
auto_refresh_time = 29
domain = ["djxs.xyz"]
forward_email = "xiyewuqiu@gmail.com"
forward_status = 1
jwt_secret = "mysecret123"
login_opacity = 0.88
many_email = 1
orm_log = false
r2_domain = "https://r2.djxs.xyz"
receive = 0
register = 0
register_verify = 1
rule_email = ""
rule_type = 0
send = 0
tg_bot_status = 1
title = "忘忧草"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
