name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "email"		#d1数据库名字
database_id = "1bceb53f-5893-4bb0-a53f-7abb807b8f38"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "b0b6379a6e3a4ebdaec6dd46f8701e60"					#kv数据库id

[[r2_buckets]]
binding = "r2"			#r2对象存储绑定名默认不可修改
bucket_name = "email"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
# 基础配置
orm_log = false
domain = ["djxs.xyz"]                    # 邮件域名，可配置多个
admin = "admin@djxs.xyz"                 # 管理员邮箱
jwt_secret = "mysecret123"      # JWT令牌密钥

# 网站基础设置 (0=开启, 1=关闭)
register = 0                            # 用户注册 (1=关闭，改为邀请制)
receive = 0                              # 邮件接收 (0=开启)
send = 0                                 # 邮件发送 (0=开启)
add_email = 1                            # 添加邮箱 (0=开启)
many_email = 1                          # 多号模式 (0=开启，允许一用户多邮箱)
auto_refresh_time = 29                   # 轮询刷新时间(秒)

# 验证设置
register_verify = 1                      # 注册人机验证 (0=开启)
add_email_verify = 1                     # 添加邮箱验证

# 个性化设置
title = "忘忧草"               # 网站标题
login_opacity = 0.88                     # 登录页透明度

# Resend 邮件发送配置
resend_token_djxs_xyz = "re_gmLpdfL6_4E35cnP6zR3fgZJTB2LrLvau"  # Resend API Token

# R2 对象存储配置
r2_domain = "https://r2.djxs.xyz"  # R2访问域名

# Turnstile 人机验证配置 (可选，防止机器人注册)
# turnstile_site_key = "your-site-key"     # Turnstile Site Key
# turnstile_secret_key = "your-secret-key" # Turnstile Secret Key

# Telegram 机器人配置 (可选，邮件推送通知)
# tg_bot_token = "your-bot-token"          # TG机器人Token
# tg_chat_id = "your-chat-id"              # TG Chat ID
tg_bot_status = 1                        # TG推送状态 (1=关闭，暂时不用)

# 邮件转发配置
forward_email = "xiyewuqiu@gmail.com"       # 转发邮箱
forward_status = 1                       # 转发状态 (1=关闭)
rule_email = ""                          # 规则邮箱
rule_type = 0                            # 规则类型 (0=全部)
